services:
  db:
    image: postgres:16.4
    restart: always
    ports:
      - "5420:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5


volumes:
  postgres_data: